// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Returns the number of affected rows so the caller can tell "deleted" from
	// "no such follow for this user" and answer 404 instead of a silent 200.
	DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) (int64, error)
	GetFeedFollows(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error)
	GetFeeds(ctx context.Context) ([]Feed, error)
	GetNextFeedsToFetch(ctx context.Context, limit int32) ([]Feed, error)
	GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error)
	GetUserByApiKey(ctx context.Context, apiKey string) (User, error)
	MarkFeedAsFetched(ctx context.Context, arg MarkFeedAsFetchedParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
