// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Returns the number of affected rows so the caller can tell "deleted" from
	// "no such follow for this user" and answer 404 instead of a silent 200.
	DeleteFeedFollow(ctx context.Context, arg DeleteFeedFollowParams) (int64, error)
	// Lets a client that got a 409 from POST /v1/feeds find the feed that already
	// holds the URL, so it can follow it. feeds.url is UNIQUE, so this is an index
	// lookup.
	GetFeedByURL(ctx context.Context, url string) (Feed, error)
	GetFeedFollows(ctx context.Context, arg GetFeedFollowsParams) ([]FeedFollow, error)
	// The trailing id keeps the ordering total, so a page boundary cannot repeat
	// or skip a feed when several share a created_at.
	GetFeeds(ctx context.Context, arg GetFeedsParams) ([]Feed, error)
	// Only feeds that are actually due are returned. Without the predicate every
	// replica of the API selects the same batch on every tick and refetches feeds
	// that were just fetched, with the duplicate inserts absorbed as conflicts so
	// nothing surfaces in the logs.
	GetNextFeedsToFetch(ctx context.Context, arg GetNextFeedsToFetchParams) ([]Feed, error)
	GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error)
	GetUserByApiKey(ctx context.Context, apiKey string) (User, error)
	// updated_at is deliberately left alone: it describes the feed's own
	// attributes, and bumping it on every pass made clients polling GET /v1/feeds
	// see every feed change once per interval when nothing had.
	MarkFeedAsFetched(ctx context.Context, arg MarkFeedAsFetchedParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
